ARG centos=7.9.2009
FROM aursu/rpmbuild:${centos}-build

USER root
RUN yum -y install \
        "libnghttp2-devel >= 1.7.0" \
        "openssl-devel >= 1.0.2" \
    && yum clean all && rm -rf /var/cache/yum

RUN yum -y --enablerepo=bintray-custom install \
        "httpd-devel >= 2.4.20" \
    && yum clean all && rm -rf /var/cache/yum
